name: WooCommerce Test Suite CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js (required for Cypress)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and Cypress
      - name: Install dependencies
        run: npm install cypress --save --dev

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: http://localhost/wordpress/
